# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d354f08713893f1d4863f2944dd7fa5b9efd8b381ccaf0011b5369ba85d9e522bab2a7175b52983acd06c6567f9ffc4b3340b603fe42372b6a6a2d9a5e11d30

test:
  secret_key_base: 898ae562b0aecb348e471107d69acf7dd8d32d65d6be834b8afe02e7b67f4ebd66613f69309fec661ea504416d5cdcabb93f81a87d4665f575a2cf3cfc308868

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
